### ISSUE TITLE
Update CMake Python code to only find Python3

### ISSUE THREAD

**Issue by Bi0T1N** [gazebosim/gz-cmake#212]
## Description
The [current approach](https://github.com/ignitionrobotics/ign-cmake/blob/ign-cmake2/cmake/IgnPython.cmake) to find Python is [deprecated since CMake 3.12](https://cmake.org/cmake/help/latest/module/FindPythonInterp.html). I also think that all Python scripts need Python3 anyway (Python2 is EOL) but [Ubuntu Bionic ships with CMake 3.10](https://packages.ubuntu.com/bionic/cmake) so a fallback is needed until it is also EOL.
My suggestion is to use the following
```cmake
if(${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.12")
    find_package(Python3)
else()
    set(PYTHON_VERSION "" CACHE STRING
    "Specify specific Python version to use ('major.minor' or 'major')")

    # if not specified otherwise use Python 3
    if(NOT PYTHON_VERSION)
    set(PYTHON_VERSION "3")
    endif()

    find_package(PythonInterp ${PYTHON_VERSION})
endif()
```
and as soon as Ubuntu Bionic reaches the EOL in April 2023 it can be removed and the [minimum CMake version be raised to 3.16](https://packages.ubuntu.com/focal/cmake).
Doing the change might need some adjustments between the different projects as e.g. `${PYTHON_VERSION}` will be `${Python3_VERSION}` in case the variables are used somewhere. 

However, there are also certain cases (e.g. [ign-math gtest](https://github.com/ignitionrobotics/ign-math/blob/ign-math6/test/gtest/cmake/internal_utils.cmake#L225), [ign-rendering gtest](https://github.com/ignitionrobotics/ign-rendering/blob/ign-rendering6/test/gtest/cmake/internal_utils.cmake#L225) and probably in every other gtest) where the code is "duplicated" instead of using the ign-cmake include.

Thus I created this issue to discuss the change before looking into each detail and making the changes.

**Comment by j-rivero** [comment]
Hello Bi0T1N:

Thanks for the proposal, I think that the approach is correct about using `find_package(Python3)` instead of the deprecated `PythonInterp`.  I agree with has no sense to keep supporting python2 anymore.

Your suggestion seems mostly fine to me, just al comment: we should try to reuse the `PYTHON_VERSION` input variable to be used under python3 to distinguish among all python3 versions possibly available in a system. A possible use case could be the generation of the python bindings for multiple python3 versions when the buildsystem needs to know the exact version of python3 to be used. Maybe a `find_package(Python3 ${PYTHON_VERSION)` can work, not sure if we would need CMake greater than 3.19 for this one. 

If you could please open a PR, we can iterate on the code. Thanks again!

**Comment by Blast545** [comment]
:man_farmer: Currently gz-math can't find python and I think it might be related to this issue.
https://build.osrfoundation.org/job/ignition_math-ci-main-focal-amd64/26/cmake/

FYI @j-rivero

**Comment by j-rivero** [comment]
arg, I thought we fixed that already, can not find the probe, maybe @scpeters?
Anyway this should help https://github.com/ignitionrobotics/ign-math/pull/402.

**Comment by azeey** [comment]
Fixed by https://github.com/gazebosim/gz-cmake/pull/213
